### ISSUE TITLE
Cannot install funpymodeling on Google Colab

### ISSUE THREAD

**Issue by sergiocalde94** [pablo14/funpymodeling#14]
Suggested by @aoelvp94 👌 

When you try to install this library in a Google Colab environment it throws an error:

```
Collecting funpymodeling
  Downloading https://files.pythonhosted.org/packages/93/09/73d42d2983e18e28e00e4a33e38eeddd1531e3f83ed91a8224f1816be81f/funpymodeling-0.1.4.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpdq9ovsms Check the logs for full command output.
```

**Comment by sergiocalde94** [comment]
The problem is that Google Colab is no compatible with python3.7 and funpymodeling requires it for work correctly (you can check pyproject.toml)

Solution:

Install conda in Google Colab environment for having python3.7

```
################################################################################
# INSTALL CONDA ON GOOGLE COLAB
################################################################################
!wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh
!chmod +x Miniconda3-py37_4.8.2-Linux-x86_64.sh
!bash ./Miniconda3-py37_4.8.2-Linux-x86_64.sh -b -f -p /usr/local

import sys


sys.path.append('/usr/local/lib/python3.7/site-packages/')
```

```
!conda install -c rdkit rdkit -y
```

You can now install funpymodeling:

```
!pip install funpymodeling
```

It throws an error because of runtime but if you click restart buttom then you are ready to use funpymodeling. You can check it on this notebook:

https://colab.research.google.com/drive/1sj4SOPvuEWJQ2OgSrZ6SMRCU6HA95_HG?usp=sharing

Let me see if this is OK for yoy @pablo14 @aoelvp94

**Comment by aoelvp94** [comment]
This problem was solved! Thank you for your time and dedication, it was very helpful!

I keep open this issue, surely @pablo14 has some words to say you!

You're crack ;)

**Comment by pablo14** [comment]
Thanks @sergiocalde94 !

Latest version gives the error:
```

ERROR: tensorflow 2.3.0 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.2 which is incompatible.
ERROR: google-colab 1.0.0 has requirement pandas~=1.0.0; python_version >= "3.0", but you'll have pandas 1.1.2 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
```
At the end:
<img width="830" alt="imagen" src="https://user-images.githubusercontent.com/9369685/92825730-42428d80-f3a6-11ea-8045-e697f5ae9cf3.png">

After the restart, it works (not before). 

Any ideas?  Maybe we need to lower the required versions in the package? thanks in advance :)

**Comment by aoelvp94** [comment]
Hello guys, according to the following log:

> Collecting funpymodeling
>  Downloading https://files.pythonhosted.org/packages/74/62/bd929c04fad618fbf7c06463b67f19ee0a99cbd7e05c925efecd7eaf92c1/funpymodeling-0.1.6-py3-none-any.whl
> Requirement already satisfied: seaborn<0.11.0,>=0.10.1 in /usr/local/lib/python3.6/dist-packages (from funpymodeling) (0.10.1)
> Collecting pandas<2.0.0,>=1.1.0
>   Downloading https://files.pythonhosted.org/packages/1c/11/e1f53db0614f2721027aab297c8afd2eaf58d33d566441a97ea454541c5e/pandas-1.1.2-cp36-cp36m-manylinux1_x86_64.whl (10.5MB)
>      |████████████████████████████████| 10.5MB 3.6MB/s 
> Collecting numpy<2.0.0,>=1.19.1
>   Downloading https://files.pythonhosted.org/packages/63/97/af8a92864a04bfa48f1b5c9b1f8bf2ccb2847f24530026f26dd223de4ca0/numpy-1.19.2-cp36-cp36m-manylinux2010_x86_64.whl (14.5MB)
>      |████████████████████████████████| 14.5MB 278kB/s 
> Collecting matplotlib<4.0.0,>=3.3.0
>   Downloading https://files.pythonhosted.org/packages/96/a7/b6fa244fd8a8814ef9408c8a5a7e4ed0340e232a6f0ce2046b42e50672c0/matplotlib-3.3.1-cp36-cp36m-manylinux1_x86_64.whl (11.6MB)
>      |████████████████████████████████| 11.6MB 149kB/s 
> Requirement already satisfied: typing-extensions<4.0.0,>=3.7.4; python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from funpymodeling) (3.7.4.3)
> Requirement already satisfied: sklearn<0.1,>=0.0 in /usr/local/lib/python3.6/dist-packages (from funpymodeling) (0.0)
> Requirement already satisfied: scipy>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from seaborn<0.11.0,>=0.10.1->funpymodeling) (1.4.1)
> Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas<2.0.0,>=1.1.0->funpymodeling) (2.8.1)
> Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas<2.0.0,>=1.1.0->funpymodeling) (2018.9)
> Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib<4.0.0,>=3.3.0->funpymodeling) (1.2.0)
> Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.6/dist-packages (from matplotlib<4.0.0,>=3.3.0->funpymodeling) (7.0.0)
> Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /usr/local/lib/python3.6/dist-packages (from matplotlib<4.0.0,>=3.3.0->funpymodeling) (2.4.7)
> Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib<4.0.0,>=3.3.0->funpymodeling) (0.10.0)
> Requirement already satisfied: certifi>=2020.06.20 in /usr/local/lib/python3.6/dist-packages (from matplotlib<4.0.0,>=3.3.0->funpymodeling) (2020.6.20)
> Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (from sklearn<0.1,>=0.0->funpymodeling) (0.22.2.post1)
> Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.7.3->pandas<2.0.0,>=1.1.0->funpymodeling) (1.15.0)
> Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->sklearn<0.1,>=0.0->funpymodeling) (0.16.0)
> ERROR: tensorflow 2.3.0 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.2 which is incompatible.
> ERROR: google-colab 1.0.0 has requirement pandas~=1.0.0; python_version >= "3.0", but you'll have pandas 1.1.2 which is incompatible.
> ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
> ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
> Installing collected packages: numpy, pandas, matplotlib, funpymodeling
>   Found existing installation: numpy 1.18.5
>     Uninstalling numpy-1.18.5:
>       Successfully uninstalled numpy-1.18.5
>   Found existing installation: pandas 1.0.5
>     Uninstalling pandas-1.0.5:
>       Successfully uninstalled pandas-1.0.5
>   Found existing installation: matplotlib 3.2.2
>     Uninstalling matplotlib-3.2.2:
>       Successfully uninstalled matplotlib-3.2.2
> Successfully installed funpymodeling-0.1.6 matplotlib-3.3.1 numpy-1.19.2 pandas-1.1.2
> WARNING: The following packages were previously imported in this runtime:
>  [matplotlib,mpl_toolkits,numpy,pandas]
> You must restart the runtime in order to use newly installed versions.

I opened an issue about this #15 , plz @pablo14 review that and his linked PR!
I think it works.

**Comment by pablo14** [comment]
Thanks both of you, now it's working!
